In [ ]:
import requests
import string
from bs4 import BeautifulSoup
url = 'https://en.wikisource.org/wiki/The_Verdict'
resp = requests.get(url)
soup = BeautifulSoup(resp.content, 'html.parser')

text = soup.get_text()

with open('Data.txt', 'w', encoding='utf-8') as file:
    file.write(text)

with open('Data.txt', 'r', encoding='utf-8') as file:
    data = file.read()

print(data[:500])





The Verdict - Wikisource, the free online library
































Download

The Verdict

From Wikisource



Jump to navigation
Jump to search
←The Verdict (1908)by Edith Wharton→




Listen to the text, read by Rena Tobey (25m19s, 13.31 MB, help | file info or download)

80998The Verdict1908Edith Wharton
I HAD always thought Jack Gisburn rather a cheap genius--though a
good fellow enough--so it was no great surprise to me to hear that,
in the height of his glory, he had dropp


In [ ]:
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([data])



In [ ]:
word_length = len(tokenizer.word_index) + 1
word_length

1233

In [ ]:
input_sequences = []
for line in text.split('\n'):
  #print(line)
  token_list = tokenizer.texts_to_sequences([line])[0]
  #print(token_list)

  for i in range(1, len(token_list)):
    my_sequence = token_list[:i + 1]

    input_sequences.append(my_sequence)
    #print(input_sequences)

In [ ]:
input_sequences

[[1, 179],
 [1, 179, 132],
 [1, 179, 132, 1],
 [1, 179, 132, 1, 429],
 [1, 179, 132, 1, 429, 430],
 [1, 179, 132, 1, 429, 430, 431],
 [1, 179],
 [52, 132],
 [264, 4],
 [264, 4, 180],
 [264, 4],
 [264, 4, 265],
 [432, 433],
 [432, 433, 266],
 [432, 433, 266, 434],
 [432, 433, 266, 434, 435],
 [436, 4],
 [436, 4, 1],
 [436, 4, 1, 267],
 [436, 4, 1, 267, 437],
 [436, 4, 1, 267, 437, 30],
 [436, 4, 1, 267, 437, 30, 438],
 [436, 4, 1, 267, 437, 30, 438, 439],
 [436, 4, 1, 267, 437, 30, 438, 439, 440],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442, 443],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442, 443, 444],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442, 443, 444, 445],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442, 443, 444, 445, 446],
 [436, 4, 1, 267, 437, 30, 438, 439, 440, 441, 442, 443, 444, 445, 446, 49],
 [436,
  4,
  1,
  267,
  437,
  30,
  438,
  439,
  440,


In [ ]:
max_len = max([len(x) for x in input_sequences])
max_len

28

In [ ]:
padded_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')
padded_sequences

array([[   0,    0,    0, ...,    0,    1,  179],
       [   0,    0,    0, ...,    1,  179,  132],
       [   0,    0,    0, ...,  179,  132,    1],
       ...,
       [   0,    0,    0, ...,  426,    3, 1226],
       [   0,    0,    0, ...,    0, 1229, 1230],
       [   0,    0,    0, ...,    0, 1231, 1232]], dtype=int32)

In [ ]:
X = padded_sequences[:,:-1]
y = padded_sequences[:,-1]

In [ ]:
import numpy as np
print(X.shape)
print(y.shape)

(3586, 27)
(3586,)


In [ ]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1], dtype=int32)

In [ ]:
y = to_categorical(y, num_classes = word_length)
y.shape

(3586, 1233)

In [ ]:
y[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Embedding(word_length, 100, input_length = 27))
model.add(LSTM(150))
model.add(Dense(word_length, activation='softmax'))


In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 27, 100)           123300    
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 1233)              186183    
                                                                 
Total params: 460083 (1.76 MB)
Trainable params: 460083 (1.76 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(X , y, epochs = 100)

Epoch 1/100
113/113 [==============================] - 12s 80ms/step - loss: 6.4733 - accuracy: 0.0365
Epoch 2/100
113/113 [==============================] - 7s 60ms/step - loss: 5.9810 - accuracy: 0.0463
Epoch 3/100
113/113 [==============================] - 11s 95ms/step - loss: 5.8436 - accuracy: 0.0535
Epoch 4/100
113/113 [==============================] - 8s 72ms/step - loss: 5.7253 - accuracy: 0.0608
Epoch 5/100
113/113 [==============================] - 6s 57ms/step - loss: 5.6222 - accuracy: 0.0619
Epoch 6/100
113/113 [==============================] - 8s 75ms/step - loss: 5.4607 - accuracy: 0.0767
Epoch 7/100
113/113 [==============================] - 7s 57ms/step - loss: 5.3277 - accuracy: 0.0837
Epoch 8/100
113/113 [==============================] - 8s 73ms/step - loss: 5.1837 - accuracy: 0.0965
Epoch 9/100
113/113 [==============================] - 6s 57ms/step - loss: 5.0435 - accuracy: 0.1046
Epoch 10/100
113/113 [==============================] - 8s 71ms/step - loss: 4.9

In [ ]:
text = "Jack Ginsburg was "
predict_next_words = 10

for _ in range(predict_next_words):
  token_text = tokenizer.texts_to_sequences([text])[0]
  #print(token_text)
  token_text = pad_sequences([token_text], maxlen = 27, padding = 'pre')
  predicted = np.argmax(model.predict(token_text), axis = -1)

  output_word = ""
  for word, index in tokenizer.word_index.items():
    if index == predicted:
      output_word = word
      break

  text += " " + output_word

print(text)

1/1 [==============================] - 0s 26ms/step
Jack Ginsburg was  that his history she believed in him gloried in him


In [ ]:
model.save('lstm_model.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
from google.colab import files
files.download('lstm_model.h5')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [40]:
import pickle
from tensorflow.keras.models import save_model

# Assuming your tokenizer is named `tokenizer`
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

# Save the model
model.save('lstm_model.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [43]:
from google.colab import drive
drive.mount('/content/drive')

# Save the model and tokenizer to Google Drive
model.save('/content/drive/MyDrive/lstm_model.h5')
with open('/content/drive/MyDrive/tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)


Mounted at /content/drive


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
